# Generated by Django 5.2.13 on 2026-04-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, el producto no aparece en la vitrina pública (oculto).'),
        ),
    ]
