# Generated by Django 5.2.13 on 2026-04-14 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_producto_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='fecha_reposicion',
            field=models.DateField(blank=True, help_text='Fecha estimada de reposición (visible si la variante está agotada).', null=True),
        ),
        migrations.AddField(
            model_name='variante',
            name='visible',
            field=models.BooleanField(default=True, help_text='Si está desmarcado, esta variante no se muestra en el catálogo público.'),
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas_catalogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcado_favorito', to='erp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'producto'), name='uniq_favorito_usuario_producto')],
            },
        ),
    ]
