# Generated by Django 5.2.13 on 2026-04-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_variante_visible_favorito_busqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='busqueda',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
