# Generated by Django 5.2.13 on 2026-04-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_busqueda_contexto_auth_user_swappable'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Archivo de imagen (tiene prioridad sobre la URL en el catálogo).', null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de la foto del producto (vitrina) si no hay archivo subido.', max_length=500, null=True),
        ),
    ]
