# Generated by Django 5.2.13 on 2026-04-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_producto_imagen'),
    ]

    def _seed_config(apps, schema_editor):
        ConfiguracionSitio = apps.get_model("erp", "ConfiguracionSitio")
        if not ConfiguracionSitio.objects.exists():
            ConfiguracionSitio.objects.create()

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tienda', models.CharField(default='Babyviip', max_length=150)),
                ('instagram_usuario', models.CharField(blank=True, default='@babyviipcl', max_length=100)),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/babyviipcl/')),
                ('facebook_nombre', models.CharField(blank=True, default='Grupo / página Babyviip', max_length=150)),
                ('facebook_url', models.URLField(blank=True, default='https://www.facebook.com/groups/1362338867173654/user/61587245798428/')),
                ('telefono', models.CharField(blank=True, default='+56 927493733', max_length=30)),
                ('correo', models.EmailField(blank=True, default='babyviip8@gmail.com', max_length=254)),
                ('direccion', models.CharField(blank=True, default='Gran Avenida 5234, local 17, San Miguel', max_length=255)),
                ('mapa_url', models.URLField(blank=True, default='https://share.google/C6HMTq54TXQDafIMq')),
                ('whatsapp_url', models.URLField(blank=True, default='https://wa.me/56927493733')),
                ('texto_bienvenida', models.TextField(blank=True, default='Ropa y accesorios para bebés desde recién nacidos hasta 3 años.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.RunPython(_seed_config, migrations.RunPython.noop),
    ]
