# Generated by Django 5.2.13 on 2026-04-14 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_configuracionsitio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_empleado',
            field=models.BooleanField(default=False, help_text='Rol interno con acceso limitado (ej: auditoría propia).'),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(blank=True, max_length=60)),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('cambio_estado', 'Cambio de estado'), ('exportar', 'Exportación')], max_length=30)),
                ('modulo', models.CharField(blank=True, max_length=100)),
                ('entidad', models.CharField(blank=True, max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
