# Generated by Django 5.2.13 on 2026-04-14 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_usuario_es_empleado_auditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='es_simulacion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('carrito', 'Por comprar'), ('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Comprado'), ('cancelado', 'Pago cancelado'), ('revertida', 'Revertida')], default='carrito', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='modo_simulacion',
            field=models.CharField(blank=True, choices=[('sin_impacto', 'Sin impacto'), ('temporal', 'Temporal'), ('permanente', 'Permanente')], max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='revertida_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='revertida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_revertidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
